### ISSUE TITLE
Setting the provisioning for a Mac Catalyst app

### ISSUE THREAD

**Issue by MortenGregersen** [cupojoe/bitrise-step-update-xcode-project-provisioning#1]
When using this step on a Mac Catalyst project, the provisioning settings are replaced for the iOS part, and it is not possible to set the provisioning settings for the macOS (Catalyst) part.

**Comment by MortenGregersen** [comment]
The configuration that should be changed:
```
PROVISIONING_PROFILE_SPECIFIER = "This is changed";
"PROVISIONING_PROFILE_SPECIFIER[sdk=macosx*]" = "This is NOT changed";
```
I have no idea how the step should be changed to accommodate this.

**Comment by cupojoe** [comment]
@MortenGregersen Thanks for the feedback. Do you have a Mac Catalyst project I could use to try to replicate this locally and fix it?

**Comment by MortenGregersen** [comment]
Yes, you can use the [https://github.com/MortenGregersen/FluxorExplorer](). It’s the project I want to setup in Bitrise.

**Comment by cupojoe** [comment]
~~@MortenGregersen can you expand a bit more on what the default settings are and what you are trying to change them to?~~ Nevermind, I figured out what you wanted to do and added the correct functionality. I'll put a PR to the bitrise peeps to release an update, but in the meantime, you can use it from this repo. Master is now up to date with the latest changes. It may take a few days for the bitrise folks to release it.

**Comment by MortenGregersen** [comment]
Awesome! Thank you @cupojoe 🥇
